---
title: "R Notebook"
output: html_notebook
---

```{r}
source("load_data.R")
source("fifa_summary.R")

library(dplyr)
```

```{r}
fifa <- load_fifa()
```


```{r}
fifa
```
```{r}
fifa %>%
  summary(G)
```

```{r}
#ratio bool
fifa %>%
  summarise(
    ratio_voted_up=mean(voted_up),
    ratio_steam_purchase=mean(steam_purchase),
    ratio_recieved_for_free=mean(recieved_for_free),
    ratio_written_during_early_access=mean(written_during_early_access)
  )
```

```{r}
compare_up_and_down()
```


```{r}
get_info_vote_by_month()
```


```{r}
#a present is a game received for free, a bad present is a presentz that got downvote
how_many_bad_present()
```

## Compare the mean value for a column between the upvotes and downvotes

```{r}
compare_mean_by_vote_status('author_playtime_last_two_weeks')
```


```{r}
compare_mean_by_vote_status('author_playtime_forever')
```

```{r}
compare_mean_by_vote_status('author_playtime_at_review')
```
```{r}
compare_mean_by_vote_status('author_num_games_owned')

```

```{r}
compare_mean_by_vote_status('author_num_reviews')

```



